import { Montserrat } from 'next/font/google'
import { clsx } from 'clsx'
import type { Metadata } from 'next'

import '../style/globals.css'

const inter = Montserrat({ subsets: ['latin', 'cyrillic'] })

export const metadata: Metadata = {
  title: 'Next.js 13 Overview',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, 'dark:bg-gray-900')}>
        <section className="dark:text-white">
          <div className="container px-6 py-10 mx-auto">{children}</div>
        </section>
      </body>
    </html>
  )
}
